### ISSUE TITLE
roar representer errors on startup

### ISSUE THREAD

**Issue by jdoconnor** [bellycard/napa#171]
may be related with roar's 1.0.0 release changing where files are stored
```
Fetching gem metadata from https://rubygems.org/.........
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 10.4.2
Using i18n 0.7.0
Using minitest 4.7.5
Using multi_json 1.10.1
Using thread_safe 0.3.4
Using tzinfo 0.3.42
Using activesupport 4.0.13
Using builder 3.1.4
Using activemodel 4.0.13
Using activerecord-deprecated_finders 1.0.3
Using arel 4.0.2
Using activerecord 4.0.13
Using addressable 2.3.6
Using ast 2.0.0
Using parser 2.2.0.2
Using astrolabe 1.3.0
Using descendants_tracker 0.0.4
Using ice_nine 0.11.1
Using axiom-types 0.1.1
Using coderay 1.1.0
Using coercible 1.0.0
Using safe_yaml 1.0.4
Using crack 0.4.2
Using database_cleaner 1.4.0
Using diff-lcs 1.2.5
Using docile 1.1.5
Using dotenv 1.0.2
Using equalizer 0.0.9
Using factory_girl 4.5.0
Using multipart-post 2.0.0
Using faraday 0.9.1
Using git 1.2.9.1
Using hashie 3.3.2
Using multi_xml 0.5.5
Using rack 1.6.0
Using rack-accept 0.4.5
Using rack-mount 0.8.3
Using virtus 1.0.4
Using grape 0.10.1
Using grape-entity 0.4.4
Using grape-swagger 0.9.0
Using json 1.8.2
Installing honeybadger 1.16.7
Using little-plugger 1.1.3
Using logging 1.8.2
Using method_source 0.8.2
Using mini_portile 0.6.2
Using mysql2 0.3.17
Using sawyer 0.6.0
Using octokit 3.7.0
Using rack-test 0.6.3
Using racksh 1.0.0
Using nokogiri 1.6.5
Using uber 0.0.13
Using representable 2.1.3
Using roar 1.0.0
Using statsd-ruby 1.2.1
Using thor 0.19.1
Using napa 0.4.0
Using powerpack 0.0.9
Using slop 3.6.0
Using pry 0.10.1
Using rack-cors 0.3.1
Using rainbow 2.0.0
Using rspec-support 3.1.2
Using rspec-core 3.1.7
Using rspec-expectations 3.1.2
Using rspec-mocks 3.1.3
Using rspec 3.1.0
Using ruby-progressbar 1.7.1
Using rubocop 0.28.0
Using shotgun 0.9
Using simplecov-html 0.8.0
Using simplecov 0.9.1
Using webmock 1.20.4
Using bundler 1.7.12
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
/t/testbar ❯❯❯ b napa c
/Users/joconnor/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/napa-0.4.0/lib/napa/output_formatters/representer.rb:2:in `require': cannot load such file -- roar/representer/json (LoadError)
	from /Users/joconnor/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/napa-0.4.0/lib/napa/output_formatters/representer.rb:2:in `<top (required)>'
	from /Users/joconnor/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/napa-0.4.0/lib/napa.rb:27:in `require'
	from /Users/joconnor/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/napa-0.4.0/lib/napa.rb:27:in `<top (required)>'
	from /Users/joconnor/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `require'
	from /Users/joconnor/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/joconnor/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `each'
	from /Users/joconnor/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/joconnor/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `each'
	from /Users/joconnor/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `require'
	from /Users/joconnor/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler.rb:134:in `require'
	from /private/tmp/testbar/app.rb:5:in `<top (required)>'
	from config.ru:1:in `require'
	from config.ru:1:in `block in <main>'
	from /Users/joconnor/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/joconnor/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /Users/joconnor/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/builder.rb:49:in `eval'
	from /Users/joconnor/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/joconnor/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/builder.rb:40:in `parse_file'
	from /Users/joconnor/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/racksh-1.0.0/lib/racksh/init.rb:23:in `init'
	from /Users/joconnor/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/napa-0.4.0/lib/napa/cli.rb:60:in `console'
	from /Users/joconnor/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/joconnor/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/joconnor/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/joconnor/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/joconnor/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/napa-0.4.0/bin/napa:5:in `<top (required)>'
	from /Users/joconnor/.rbenv/versions/2.1.5/bin/napa:23:in `load'
	from /Users/joconnor/.rbenv/versions/2.1.5/bin/napa:23:in `<main>'
```

**Comment by jdoconnor** [comment]
for completeness.... using ruby 2.1.5

**Comment by jdoconnor** [comment]
looks like @ywong19 patched this up after the latest release (https://github.com/bellycard/napa/commit/84e6fd8349426ac0f2e7da6715f800ef44d24094) by keeping roar to the pre-1.0.0 release. If you want to keep this open to thwart other issue writers, feel free, but this can be closed.
